const { bootAdmin, escapeHtml, showPageMessage } = window.AdminShared;
bootAdmin(['admin','editor'], async ({ supabase, session }) => {
 const homeForm=document.querySelector('[data-home-form]'); const lists=document.querySelector('[data-home-lists]'); let homeId=null;
 const load=async()=>{ const {data:home}=await supabase.from('homepage_settings').select('*').eq('is_active',true).is('deleted_at',null).maybeSingle(); if(home){homeId=home.id; Object.entries(home).forEach(([k,v])=>{ if(homeForm.elements[k]) homeForm.elements[k].value=v||''; });}
 const [stats,partners,testimonials]=await Promise.all(['impact_statistics','partner_logos','testimonials'].map(t=>supabase.from(t).select('*').is('deleted_at',null).order('sort_order'))); lists.innerHTML=`<h3>Stats</h3>${(stats.data||[]).map(x=>`<p>${escapeHtml(x.value)} — ${escapeHtml(x.label)}</p>`).join('')}<h3>Partners</h3>${(partners.data||[]).map(x=>`<p>${escapeHtml(x.name)}</p>`).join('')}<h3>Testimonials</h3>${(testimonials.data||[]).map(x=>`<p>“${escapeHtml(x.quote)}”</p>`).join('')}`; };
 homeForm.onsubmit=async(e)=>{ e.preventDefault(); const values=Object.fromEntries(new FormData(homeForm).entries()); values.updated_by=session.user.id; const q=homeId?supabase.from('homepage_settings').update(values).eq('id',homeId):supabase.from('homepage_settings').insert({...values,is_active:true}); const {error}=await q; if(error) throw error; showPageMessage('Homepage saved.','success'); await load(); };
 const simple=(sel,table,extra={})=>{document.querySelector(sel).onsubmit=async(e)=>{e.preventDefault(); const f=e.currentTarget; const v=Object.fromEntries(new FormData(f).entries()); ['featured','consent_confirmed'].forEach(k=>{if(f.elements[k]) v[k]=f.elements[k].checked}); v.is_active=true; v.created_by=session.user.id; Object.assign(v,extra); const {error}=await supabase.from(table).insert(v); if(error) throw error; f.reset(); showPageMessage('Item added.','success'); await load();};};
 simple('[data-stat-form]','impact_statistics'); simple('[data-partner-form]','partner_logos'); simple('[data-testimonial-form]','testimonials',{featured:true}); await load();
});
