const { bootAdmin, escapeHtml, showPageMessage, uploadFile, validateFile } = window.AdminShared;
bootAdmin(['admin','editor','media_manager'], async ({ supabase, session }) => {
  const form = document.querySelector('[data-media-form]'); const list = document.querySelector('[data-media-list]'); const fileInput = document.querySelector('[data-files]'); const progress = document.querySelector('[data-upload-progress]');
  const eventsSelect = document.querySelector('[data-events]');
  const { data: events, error: eventsError } = await supabase.from('events').select('id,title').is('deleted_at', null).order('event_date', { ascending: false }); if (eventsError) throw eventsError;
  eventsSelect.innerHTML = (events || []).map(e => `<option value="${e.id}">${escapeHtml(e.title)}</option>`).join('');
  const load = async () => { const { data, error } = await supabase.from('event_media').select('*, events(title)').is('deleted_at', null).order('created_at', { ascending:false }); if (error) throw error; list.innerHTML = (data||[]).map(m => `<article class="media-card">${m.media_type === 'image' ? `<img src="${m.public_url}" alt="${escapeHtml(m.alt_text || m.caption || 'Event image')}">` : `<video src="${m.public_url}" controls></video>`}<h3>${escapeHtml(m.caption || 'Untitled media')}</h3><p>${escapeHtml(m.events?.title || '')}</p><p>${m.approval_status} · ${m.visibility} · consent: ${m.consent_confirmed ? 'yes':'no'}</p><div class="actions"><button class="btn btn-light" data-approve="${m.id}">Approve public</button><button class="btn btn-secondary" data-cover="${m.id}:${m.event_id}:${m.public_url}">Set cover</button><button class="btn btn-danger" data-hide="${m.id}">Hide</button></div></article>`).join('') || '<p>No media uploaded yet.</p>'; document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>update(b.dataset.approve,{approval_status:'approved',visibility:'public'})); document.querySelectorAll('[data-hide]').forEach(b=>b.onclick=()=>update(b.dataset.hide,{visibility:'private'})); document.querySelectorAll('[data-cover]').forEach(b=>b.onclick=()=>setCover(...b.dataset.cover.split(':'))); };
  const update = async (id, patch) => { const { error } = await supabase.from('event_media').update(patch).eq('id', id); if (error) throw error; await supabase.rpc('log_audit_event',{entity_type:'event_media',entity_id:id,action:'update'}); await load(); };
  const setCover = async (mediaId, eventId, ...urlParts) => { const publicUrl = urlParts.join(':'); const { data: mediaRow, error: mediaReadError } = await supabase.from('event_media').select('consent_confirmed, approval_status, visibility').eq('id', mediaId).single(); if (mediaReadError) throw mediaReadError; if (!mediaRow.consent_confirmed) return showPageMessage('Confirm consent before using media as a cover image.', 'warning'); const mediaUpdate = await supabase.from('event_media').update({ approval_status: 'approved', visibility: 'public' }).eq('id', mediaId); if (mediaUpdate.error) throw mediaUpdate.error; const eventUpdate = await supabase.from('events').update({ cover_media_id: mediaId, cover_image_url: publicUrl }).eq('id', eventId); if (eventUpdate.error) throw eventUpdate.error; await supabase.rpc('log_audit_event',{entity_type:'events',entity_id:eventId,action:'set_cover_media',metadata:{media_id:mediaId}}); await load(); };
  document.querySelector('[data-drop-zone]').addEventListener('drop', e => { e.preventDefault(); fileInput.files = e.dataTransfer.files; }); document.querySelector('[data-drop-zone]').addEventListener('dragover', e => e.preventDefault());
  form.addEventListener('submit', async (e) => { e.preventDefault(); const files = [...fileInput.files]; if (!files.length) return showPageMessage('Choose at least one file.'); const fd = new FormData(form); for (const file of files) { const isImage = file.type.startsWith('image/'); validateFile(file, isImage ? 'image' : 'video'); const uploaded = await uploadFile(supabase, isImage ? 'event-images':'event-videos', file, fd.get('event_id'), (m)=>progress.innerHTML=`<div class="notice success">${escapeHtml(m)}</div>`); const row = { event_id: fd.get('event_id'), media_type: isImage ? 'image':'video', file_path: uploaded.path, public_url: uploaded.publicUrl, caption: fd.get('caption'), alt_text: fd.get('alt_text'), consent_confirmed: form.consent_confirmed.checked, approval_status: fd.get('approval_status'), visibility: fd.get('visibility'), sort_order: Number(fd.get('sort_order')||0), uploaded_by: session.user.id }; const { data, error } = await supabase.from('event_media').insert(row).select().single(); if (error) throw error; await supabase.rpc('log_audit_event',{entity_type:'event_media',entity_id:data.id,action:'upload'}); } form.reset(); showPageMessage('Upload complete.', 'success'); await load(); });
  await load();
});
